name: Move Issue to "In Progress" on Comment

on:
  issue_comment:
    types: [created]

jobs:
  move_issue_to_in_progress:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: write
    steps:
      - name: Move issue to 'In Progress' if comment contains 'on it'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment.body.toLowerCase();
            const projectId = "PVT_kwHOCvwGBc4AqQdO"; 
            const fieldId = "PVTSSF_lAHOCvwGBc4AqQdOzghiJMQ"; // Status field ID
            const inProgressOptionId = "f75ad846"; // Option ID for "In Progress"
            
            // Check if the comment contains 'on it'
            if (comment.includes('on it')) {
              console.log(`Checking open issues for project ${projectId} based on comment: ${comment}`);
              
              // Query for open issues in the project
              const query = `
                query {
                  node(id: "${projectId}") {
                    ... on ProjectV2 {
                      items(first: 100) {
                        nodes {
                          id
                          content {
                            ... on Issue {
                              id
                              number
                              title
                              state
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `;

              const response = await github.graphql(query);
              const openIssues = response.node.items.nodes.filter(issue => issue.content.state === 'OPEN');
              
              // Move each open issue to "In Progress"
              for (const issue of openIssues) {
                const issueId = issue.content.id;
                console.log(`Moving issue #${issue.content.number} to "In Progress"`);
                
                // Update the status field to "In Progress"
                await github.graphql(`
                  mutation {
                    updateProjectV2ItemFieldValue(input: {
                      projectId: "${projectId}",
                      itemId: "${issueId}",
                      fieldId: "${fieldId}",
                      value: { singleSelectOptionId: "${inProgressOptionId}" }
                    }) {
                      projectV2Item {
                        id
                      }
                    }
                  }
                `);

                console.log(`Moved issue #${issue.content.number} to "In Progress"`);
              }
            } else {
              console.log(`Comment does not contain 'on it'; action skipped.`);
            }
