name: Move Assigned Issues to Project Column

on:
  issues:
    types:
      - assigned 

jobs:
  move-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Move Issue to 'In Progress' Column
      uses: alex-page/github-project-automation-plus@v0.3.0
      with:
        project: 'Bryan-atu' 
        column: 'In Progress'       
        repo-token: ${{ secrets.PAT_TOKEN }}

    - name: Debug GitHub API Response
      run: |
        curl -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/projects

