name: Move Issue to "In Progress" on Comment

on:
  issue_comment:
    types: [created]

jobs:
  move_issue_to_in_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to 'In Progress' if comment contains 'on it'
        uses: actions/github-script@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          script: |
            const comment = context.payload.comment.body.toLowerCase();
            const projectId = "PVT_kwHOCvwGBc4AqQdO"; 

            // Check if the comment contains 'on it'
            if (comment.includes('on it')) {
              console.log(`Checking open issues for project ${projectId} based on comment: ${comment}`);
              
              // Query for open issues in the project
              const query = `
                query {
                  node(id: "${projectId}") {
                    ... on ProjectV2 {
                      items(first: 100) {
                        nodes {
                          id
                          content {
                            ... on Issue {
                              id
                              number
                              title
                              state
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `;

              const response = await github.graphql(query);
              const openIssues = response.node.items.nodes.filter(issue => issue.content.state === 'OPEN');
              
              // Move each open issue to "In Progress"
              for (const issue of openIssues) {
                const issueId = issue.content.id;
                console.log(`Moving issue #${issue.content.number} to "In Progress"`);
                
                // Add the issue to the "In Progress" column
                await github.graphql(`
                  mutation {
                    addProjectV2ItemById(input: {
                      projectId: "${projectId}",
                      contentId: "${issueId}"
                    }) {
                      item {
                        id
                      }
                    }
                  }
                `);

                console.log(`Moved issue #${issue.content.number} to "In Progress"`);
              }
            } else {
              console.log(`Comment does not contain 'on it'; action skipped.`);
            }