name: Move Issue to "In Progress" on Comment

on:
  issue_comment:
    types: [created]

jobs:
  move_issue_to_in_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to 'In Progress' if comment contains 'on it'
        uses: actions/github-script@v6
        with:
          script: |
            const comment = context.payload.comment.body.toLowerCase();
            const issueNumber = context.payload.issue.number;
            const columnName = "In Progress";  // Name of the column
            const projectId = PVT_kwHOCvwGBc4AqQdO;  

            // Check if the comment includes the phrase "on it"
            if (comment.includes('on it')) {
              console.log(`Moving issue #${issueNumber} to "In Progress" column based on comment: ${comment}`);

              // Define GraphQL mutation to move the issue
              const mutation = `
                mutation {
                  addProjectV2ItemById(input: {
                    projectId: "${projectId}",
                    contentId: "${issueNumber}"
                  }) {
                    item {
                      id
                    }
                  }
                }
              `;

              // Send GraphQL request to GitHub
              const response = await github.graphql(mutation);
              console.log(`Moved issue #${issueNumber} to the "In Progress" column.`);
            } else {
              console.log(`Comment does not contain 'on it'; action skipped.`);
            }

