name: Move Assigned Issues to Project Column

on:
  issues:
    types:
      - assigned 

jobs:
  move-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Move Issue to 'In Progress' Column
      uses: alex-page/github-project-automation-plus@v0.3.0
      with:
        project: 'Bryan-atu' 
        column: 'In Progress'       
        repo-token: ${{ secrets.GITHUB_TOKEN }}

